spring:
  application:
  name: dbProject
  # DataSource Config
  datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://47.96.165.184:3306
  username: codeep
  password: jacket123456
server:
  port: 8080
